version: '2'
services:
  rabbitmq:
     image: rabbitmq:3-management
     environment:
         - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
     volumes:
       - rabbitmq-data:/var/lib/rabbitmq

  # influxdb:
  #   image: influxdb:latest
  #   ports:
  #       - "8083:8083"
  #       - "8086:8086"
  #       - "8090:8090"
  #
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  validator:
    image: zwant/ngcd-validator
    command: python -u validator/run.py
    environment:
      - RABBITMQ_HOST=rabbitmq
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  event-writer:
    image: zwant/ngcd-event-writer
    command: python -u event_writer/run.py
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres@postgres:5432/event_api
      - RABBITMQ_HOST=rabbitmq
      - CLEAN_DB=false
    depends_on:
      - "rabbitmq"
      - "postgres"

  publisher-lb:
    ports:
      - 5001:8080
    image: rancher/load-balancer-service
    links:
      - publisher:publisher

  publisher:
    image: zwant/ngcd-publisher
    command: flask run -p 8080 -h 0.0.0.0
    expose:
      - "8080"
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672//
      - FLASK_APP=publisher.app
      - FLASK_DEBUG=true
    depends_on:
      - "rabbitmq"

  event-api-lb:
    ports:
      - 5000:8080
    image: rancher/load-balancer-service
    links:
      - event-api:event-api

  event-api:
    image: zwant/ngcd-event-api
    command: flask run -p 8080 -h 0.0.0.0
    expose:
      - "8080"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres@postgres:5432/event_api
      - FLASK_APP=event_api.app
      - FLASK_DEBUG=true
      - CLEAN_PROJECTION_DB=false
      - PROJECTION_STORE_BACKEND_TYPE=inmemory
      - EVENT_STORE_BACKEND_TYPE=sqlalchemy
      - EVENT_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres@postgres:5432/event_api
    links:
      - postgres
    depends_on:
      - postgres

  ui-lb:
    ports:
      - 80:80
    image: rancher/load-balancer-service
    links:
      - ui:ui

  ui:
    image: zwant/ngcd-ui
    expose:
      - "80"
    links:
      - event-api
    depends_on:
      - event-api

volumes:
  postgres-data:
    driver: local

  rabbitmq-data:
    driver: local
