export const LOAD_PIPELINE_DETAILS = 'ngcd/PipelineListItem/LOAD_PIPELINE_DETAILS';
export const LOAD_PIPELINE_DETAILS_SUCCESS = 'ngcd/PipelineListItem/LOAD_PIPELINE_DETAILS_SUCCESS';
export const LOAD_PIPELINE_DETAILS_ERROR = 'ngcd/PipelineListItem/LOAD_PIPELINE_DETAILS_ERROR';
