version: 1
disable_existing_loggers: false
formatters:
    simple:
        format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    publisher:
        propagate: true
    amqp:
        level: INFO
    werkzeug:
        propagate: true
root:
    handlers: [console]
    level: DEBUG
